#!/bin/sh

# run from this directory
cd ${0%/*} || exit 1

# trap on error
set -e

# check if OpenFOAM has been sourced
if [ -z "$WM_PROJECT" ]; then
	echo "Please source OpenFOAM bashrc first!"
	exit 1
fi

# clean libraries
(cd viscoelastic && wclean libso)

# clean solver
(cd viscoelasticSimpleFoam && wclean)

# clean third party
(cd thirdparty && ./Allwclean)
